r"""Stage Pascal sources under 8.3 names, drive a real Turbo Pascal under
DOSBox-X, and read the compiler's output back.

    python kit/tools/pascal/build.py CONFIG.toml            everything
    python kit/tools/pascal/build.py CONFIG.toml VGA        one target
    python kit/tools/pascal/build.py CONFIG.toml --selftest prove the toolchain
    python kit/tools/pascal/build.py CONFIG.toml --compiler tp6
    python kit/tools/pascal/build.py CONFIG.toml --sw=/$G-  one extra switch

THREE SCRIPTS, ONE TOOL. `dosbuild.py`, `build.py` and `vtbuild.py` -- 993
lines across two repositories -- did the same six things: stage sources into a
DOS-visible directory under 8.3 names, order the targets so a unit precedes
whatever uses it, write a batch file, run DOSBox-X with a timeout, read the log
back from the host, and install what came out. What differed was DATA, and it
is now a config file per target, so no machine path is written down twice.

**A NOTE ON THE WORD.** The ticket calls this a build harness. `harness` is
taken: in this method's vocabulary it is a small program that runs one piece of
the SUBJECT so a person can watch it -- `TPART3.EXE` is a harness. This is the
thing that BUILDS those, so it is `build.py`. See `kit/wiki/CONTEXT.md`.

THE DOSBOX CONFIG IS GENERATED, ALWAYS, and that is a fix rather than a
preference. Two of the three scripts pointed at a committed `.conf` holding
`D:\source\psycho\build` and `D:\DOSBox-X\Machine\HDD` -- machine paths in a
committed file, which the standing rules forbid outright. The third already
generated its own. Generating it puts every machine path in `kit.local.toml`
where it belongs, and makes the mount agree with the staging directory by
construction rather than by somebody remembering.

WHAT IS PASSED IN, never built in: the compiler and its switch line, the
assembler and its flags, the 8.3 name map, the ordering strategy, the source
encoding, the dialect, the target list and where the result is installed. The
switch line is the one to be careful with, because getting it wrong does not
fail -- it produces a build that MEASURES wrong. TP7 defaults stack checking
ON, and with it on every framed procedure, INCLUDING an `assembler` one, opens
with a seven-byte `XOR AX,AX / CALLF` before the body; leaving the default made
every hand-transcribed routine differ from the binary in its opening bytes.

WHAT IS NOT COMPARABLE AFTERWARDS. `.TPU` and `.OBJ` files embed a timestamp,
so two builds of identical source do not hash the same. Measured: across two
consecutive full builds of this demo, all 243 staged and built files differ in
three places and **all 35 `.EXE` files are byte-identical**. So an executable
is the unit of a reproducibility check here, and a `.TPU` never is -- which is
why the unit instruments compare a `.TPU`'s CODE section rather than its bytes.
"""
import io
import re
import shutil
import subprocess
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[0]))
import project                                    # noqa: E402

try:
    import tomllib
except ModuleNotFoundError:                       # pragma: no cover -- 3.11+
    import tomli as tomllib                       # type: ignore


NL = chr(10)                  # written literally so no escape is at risk
SEP = chr(92)                 # a DOS path separator

SELFTEST = """program Hello;
{ Toolchain self-test: proves the compiler runs and produces an executable. }
var
  I : Integer;
begin
  WriteLn('toolchain self-test OK');
  for I := 1 to 3 do WriteLn('  line ', I);
end.
"""

CONF_TEMPLATE = """\
# DOSBox-X configuration, GENERATED by kit/tools/pascal/build.py.
# Edit the build config or kit.local.toml, never this file.
#
# Drives:
#     C:  {hdd}
#     {drive}:  {build}
{mountdoc}
[sdl]
autolock    = false
waitonerror = false

[dosbox]
machine  = svga_s3
memsize  = 16
captures = capture
title    = {title}

[cpu]
core    = auto
cputype = pentium_ii
cycles  = max

[render]
frameskip = 0
aspect    = false

[mixer]
nosound = true

[dos]
xms = true
ems = true
umb = true
# Long filenames OFF. The compiler is a real-mode tool from 1993 and
# everything staged is 8.3 anyway; LFN only invites surprises.
lfn = false

[autoexec]
mount C {hdd}
mount {drive} {build}
{mounts}set PATH=%PATH%;{binpath}
{drive}:
call {drive}:\\BUILD.BAT
exit
"""


# ---------------------------------------------------------------------------
# The config, and the answers behind it


def read_config(path):
    with io.open(path, "rb") as fh:
        cfg = tomllib.load(fh)
    cfg.setdefault("order", {}).setdefault("mode", "uses")
    cfg.setdefault("stage", {}).setdefault("encoding", "ascii")
    cfg.setdefault("names", {})
    cfg.setdefault("assembler", {})
    cfg.setdefault("install", {})
    if "compiler" not in cfg:
        raise SystemExit("  %s: no [compiler] section" % path)
    return cfg


def tool_missing(dos_path):
    """A DOS path that does not exist on the mounted drive, or None.

    WHY THIS IS NOT PARANOIA. DOS does not set ERRORLEVEL when it cannot find a
    command -- it prints "Bad command or filename" and carries on with errorlevel
    zero. So the batch file's `if errorlevel 1` can never catch a missing
    compiler, and it did not: on one project whose config still named an old
    install path, every unit was stamped ** OK, the build printed
    "all N target(s) compiled" and exited 0 while TPC.EXE was never invoked once.
    A build that cannot find its compiler reported success.

    The drive letter is resolved through dosbox.hdd, which is the same mapping
    the generated config mounts, so this checks the path DOS will actually use.
    """
    if not dos_path or len(dos_path) < 3 or dos_path[1] != ":":
        return None                       # not a drive-qualified path; leave it
    try:
        hdd = pathlib.Path(machine("dosbox.hdd"))
    except Exception:
        return None                       # no mapping to check against
    if dos_path[0].upper() != "C":
        return None                       # only C: is the mounted image
    rel = dos_path[3:].replace("\\", "/")
    return dos_path if not (hdd / rel).exists() else None


def bin_dir(cfg, compiler):
    """The DOS directory holding this compiler, off the answer that INVOKES it.

    `binpath` in a build config was a MACHINE PATH IN A COMMITTED FILE, which
    is the one thing machine() below exists to prevent -- and it went stale
    exactly as that rule predicts. Three installs were renamed; the
    `toolchain.*` answers were corrected in kit.local.toml and the committed
    `binpath` copies were not, because nothing compiles through them: every
    invocation BUILD.BAT writes is fully qualified, so the PATH line they feed
    is read by nobody during a build. It is read at the interactive prompt,
    where a renamed directory answers "Bad command or filename" -- which is
    the incident recorded in write_overlay.

    Measured 4 Sep 2026 across every build config in both consumers: 15 typed
    values stale in one, 4 correct in the other, and this derivation reproduces
    all 4 while replacing all 15 with a directory that exists. Nothing is
    underivable -- the compiler cannot be invoked without `toolchain.<section>`
    in the first place, so deriving from it adds no requirement.

    The same shape was already half-present: write_overlay derived TASM's
    directory from `toolchain.tasm` while taking the compiler's from the
    config, so in one list the derived entry was right and the typed one wrong.
    """
    comp = cfg["compiler"][compiler]
    exe = machine("toolchain." + compiler, comp.get("exe"))
    if exe and SEP in exe:
        return exe.rsplit(SEP, 1)[0]
    # No answer and no exe: the build cannot run at all, and main() says so
    # with a better message than a PATH line could.
    return comp.get("binpath", "C:" + SEP + "TP" + SEP + "BIN")


def machine(key, fallback=None):
    """A machine path, from kit.local.toml. Never from a committed file."""
    try:
        return project.get(key)
    except project.Missing:
        if fallback is not None:
            return fallback
        raise


# ---------------------------------------------------------------------------
# Staging


def dos_text(text, encoding):
    """The source as the DOS compiler will see it.

    `binary` copies bytes untouched, which is what a release tree of latin-1
    sources with accented comments needs. Everything else round-trips through
    the named encoding so a character the compiler cannot read becomes visible
    here rather than as an error forty lines from its cause.
    """
    if encoding in ("binary", "bytes"):
        return text
    return text.encode(encoding, errors="replace").decode(encoding)


def tp6_dialect(text, restore="{$F-}"):
    """Replace an interface's `far` directives with an `{$F+}` region.

    A COMPILER FACT, not a project's, which is why it travels: Turbo Pascal 6
    has no `far` directive on a unit's exported routines at all. It rejects one
    on the interface declaration (error 73) and on the implementation header of
    a routine the interface already declared (error 36). The calling model comes
    from `{$F}` at the point of declaration and nowhere else; TP7 relaxed that.

    So the rewrite is a SWITCH rather than a moved directive -- `{$F+}` after
    the interface keyword, restored at the implementation keyword. That keeps
    the interface's routines far and the implementation's private ones near,
    which is the TP7 shape. Turning `{$F+}` on for the whole unit would promote
    the private routines too.
    """
    tail = r"(?:\s*\([^()]*\))?(?:\s*:\s*\w+)?\s*;"
    iface = re.search(r"(?im)^interface\b[ \t]*$", text)
    impl = re.search(r"(?im)^implementation\b", text)
    if not (iface and impl):
        return text
    head, body = text[: impl.start()], text[impl.start():]
    n = 0

    def strip(m):
        nonlocal n
        n += 1
        return m.group(1)

    # The declaration is matched WHOLE rather than up to the first semicolon: a
    # parameter list separates its groups with semicolons too, so `[^;]*` stops
    # short on every routine taking more than one group.
    head = re.sub(r"(?is)(\b(?:procedure|function)\s+\w+\b" + tail +
                  r")\s*far\s*;", strip, head)
    if not n:
        return text                       # nothing exported far -- leave alone
    head = head[: iface.end()] + "\n{$F+}" + head[iface.end():]
    return head + body.replace("implementation", "implementation\n" + restore, 1)


DIALECTS = {"": lambda t: t, "tp7": lambda t: t, "tp6": tp6_dialect}


def rename_source(text, name83, names):
    """Rewrite the unit name, `uses` clauses and `{$I}` paths for 8.3 DOS.

    The unit identifier inside a file is independent of the filename, but the
    compiler finds a unit BY FILENAME -- so `uses Part3Sprites` has to become
    `uses P3Sprite` the moment PART3_SPRITES.PAS is staged as P3SPRITE.PAS.
    """
    row = names.get(name83)
    if not row:
        return text
    _, unit_old, unit_new = row
    text = re.sub(r"(?im)^(\s*unit\s+)%s(\s*;)" % re.escape(unit_old),
                  r"\g<1>%s\g<2>" % unit_new, text)
    # NOT INSIDE A STRING LITERAL. This is a case-insensitive \bword\b sweep
    # over the whole file, so a map row like PSYCHO.PAS -> Psycho rewrote the
    # literal in ShowString(' MEGADEMO, PSYCHO NEUROSIS!!! ') to `Psycho` and
    # changed the demo's own banner text -- a 3-byte coverage span that reading
    # the source could never explain, because the source was right and the
    # staged copy was not. Comments are skipped for the same reason in reverse:
    # rewriting them makes the staged file lie about where it came from.
    parts = re.split(r"('(?:''|[^'])*'|\{[^}]*\}|\(\*.*?\*\))", text, flags=re.S)
    for i in range(0, len(parts), 2):           # even indices are code
        for _, old, new in names.values():
            parts[i] = re.sub(r"(?i)\b%s\b" % re.escape(old), new, parts[i])
    text = "".join(parts)
    # {$I gen/P3PAL.INC} -> {$I GEN\P3PAL.INC}
    text = re.sub(r"(?i)\{\$I\s+([a-z0-9_]+)/([A-Z0-9_]+\.INC)\s*\}",
                  lambda m: "{$I %s\\%s}" % (m.group(1).upper(), m.group(2)),
                  text)
    return text


def outdir(cfg, build, keep=False):
    """The directory the build's PRODUCTS go in, or the build root if unset.

    `[stage] output = "BIN"` separates what a build MAKES from what it was
    given: sources staged flat, includes in their own directories, and every
    .OBJ, .TPU, .MAP and .EXE in one place. Unset, everything lands in the
    build root, which is what every project did before this existed and what
    the kit still does by default.

    The compiler is what makes this possible rather than a copying step
    afterwards: TP's `/E` is documented as the EXE *and TPU* output directory,
    `/O` gives the object search path, and `/U` the unit search path -- so the
    products can be written straight there and found there.
    """
    name = (cfg.get("stage", {}) or {}).get("output")
    if not name:
        return build
    d = build / name.upper()
    wipe(d, keep)
    return d


def wipe(d, keep=False):
    """Empty the staging directory. FILES AND DIRECTORIES BOTH.

    It used to unlink files only, so a subdirectory left by a retired step
    survived every build for ever -- two of them had been sitting in one
    project's staging directory for ten days, empty, outliving the tools that
    made them. Include directories are created by `stage` immediately after this
    runs, so removing them here is safe and is what makes the staging directory
    mean "what this build needs" rather than "what every build ever needed".
    """
    d.mkdir(parents=True, exist_ok=True)
    if keep:
        return
    for f in d.glob("*"):
        if f.is_file():
            f.unlink()
        else:
            shutil.rmtree(f, ignore_errors=True)


def stage(cfg, root, build, compiler, selftest=False, keep=False):
    """Put everything the compiler needs into the mounted directory.

    Returns the staged target filenames, in config order. `keep` leaves what is
    already there -- see the note on it in `main`.
    """
    wipe(build, keep)
    if selftest:
        # THE OUTPUT DIRECTORY HAS TO EXIST HERE TOO. The selftest returns
        # early, which skipped creating it, and TP does not create an output
        # directory it was given -- it answers `Error 14: Invalid filename
        # (D:\BIN\HELLO.EXE)`. So the one command whose whole job is to prove
        # the toolchain works was the one command that could not run.
        outdir(cfg, build, keep)
        (build / "HELLO.PAS").write_text(SELFTEST, encoding="ascii")
        return ["HELLO.PAS"]

    st = cfg["stage"]
    enc = st["encoding"]
    names = {k: tuple(v) for k, v in cfg["names"].items()}
    src = root / cfg.get("src", "src")
    # Sources whose 8.3 name and unit identifier are ALREADY right map to
    # themselves. Generated test harnesses are the case this exists for: they
    # are emitted with conforming names, so listing each one here would be a
    # second copy of a fact their generator already guarantees, and it would go
    # stale the first time somebody added one.
    # THE KEY IS THE PATH RELATIVE TO src, NOT THE BASENAME, because `order`
    # entries are resolved as `src / name` further down. Keying on the basename
    # worked only while every source sat directly in src/: the moment a project
    # moved its test harnesses into a subdirectory, the glob still found them,
    # still mapped them, and then `src / "TP1S1.PAS"` did not exist -- and the
    # loop below skips a missing file QUIETLY, by design, so 22 targets would
    # have stopped being built with nothing said. The 8.3 DOS name stays the
    # basename: DOS has no subdirectory in the staged build.
    identity = []
    for pat in st.get("identity", []):
        for f in sorted(src.glob(pat)):
            rel = f.relative_to(src).as_posix()
            if rel not in names:
                names[rel] = (f.name, f.stem, f.stem)
                identity.append(rel)
    dialect = DIALECTS[cfg["compiler"][compiler].get("dialect", "")]

    # Include directories staged as subdirectories of the mounted drive, so a
    # rewritten `{$I GEN\X.INC}` resolves. Each entry is `name = "path"`.
    for sub, rel in sorted(st.get("subdirs", {}).items()):
        out = build / sub.upper()
        wipe(out, keep)
        for f in sorted((root / rel).glob("*")):
            if f.is_file():
                shutil.copy(f, out / f.name.upper())

    # Files that travel beside the sources but are not compiled in their own
    # right: assembler modules, includes, object modules, data. Copied flat
    # into the build root, because the assembler resolves INCLUDE relative to
    # the current directory and the compiler looks for a `{$L}` object next to
    # the unit that links it.
    for pat in st.get("alongside", []):
        for f in sorted(root.glob(pat)):
            if f.is_file():
                shutil.copy(f, build / f.name.upper())

    # Directories copied AS DIRECTORIES, contents untouched. `alongside` above
    # flattens into the build root and uppercases as it goes, which is right
    # for a file the compiler must find beside a unit and wrong for a folder
    # somebody wants to see arrive unchanged. The assembler's own INCLUDE still
    # resolves relative to the current directory, so the batch below changes
    # into the directory before assembling rather than passing a path -- which
    # keeps that resolution exactly as it was when these files sat in the root.
    for rel in st.get("verbatim", []):
        d = root / rel
        if not d.is_dir():
            continue
        out = build / d.name.upper()
        wipe(out, keep)
        for f in sorted(d.glob("*")):
            if f.is_file():
                shutil.copy(f, out / f.name)

    products = outdir(cfg, build, keep)

    staged = []
    order = list(cfg["order"].get("list") or [])
    if not order:
        order = sorted(names) or sorted(p.relative_to(src).as_posix() for p in src.rglob("*.PAS"))
    # Identity-mapped sources are appended AFTER the declared list, the way the
    # script this replaces appended them to its name map. They are leaves that
    # nothing else uses, so where they sit only matters in that they must be
    # staged at all -- and leaving them out of the order silently built 38
    # targets instead of 67, with every one that ran reporting success.
    order += [n for n in identity if n not in order]
    for name in order:
        p = src / name
        if not p.exists():
            continue                      # not transcribed yet -- skip quietly
        name83 = names.get(name, (name,))[0]
        if enc in ("binary", "bytes"):
            shutil.copy(p, build / name83.upper())
        else:
            text = p.read_text(encoding="utf-8", errors="replace")
            text = rename_source(text, name, names) if names else text
            text = dialect(text)
            (build / name83.upper()).write_text(dos_text(text, enc),
                                                encoding=enc, errors="replace")
        staged.append(name83.upper())
    return staged


# ---------------------------------------------------------------------------
# Linting


def lint_sources(root, cfg):
    """Run the project's own Pascal checker over the sources it is about to
    build. Returns the number of problems, having printed them.

    `lint` names the script; its `check(path)` is imported and called. The
    files are the config's own order plus whatever the identity globs pick up,
    so the check covers exactly what the build covers -- no more, and never
    less because a directory constant pointed somewhere else.
    """
    spec = cfg["lint"]
    script = spec if isinstance(spec, str) else spec.get("script")
    sys.path.insert(0, str((root / script).parent))
    try:
        mod = __import__(pathlib.Path(script).stem)
        check = getattr(mod, "check")
    except Exception as exc:              # absent, unimportable, or no check()
        print("  linter %s unavailable (%s) -- NOT skipped silently" % (script, exc))
        return 0
    src = root / cfg.get("src", "src")
    wanted = list(cfg["order"].get("list") or [])
    for pat in cfg["stage"].get("identity", []):
        wanted += [f.relative_to(src).as_posix()
                   for f in sorted(src.glob(pat))
                   if f.relative_to(src).as_posix() not in wanted]
    if not wanted:
        wanted = sorted(p.relative_to(src).as_posix() for p in src.rglob("*.PAS"))
    total = 0
    for name in wanted:
        f = src / name
        if not f.exists():
            continue
        probs = check(f)
        if probs:
            print("")
            print("=== %s ===" % f.name)
            for ln, msg in probs:
                print("  line %4d  %s" % (ln, msg))
            total += len(probs)
    return total


# ---------------------------------------------------------------------------
# Ordering


USES = re.compile(r"(?is)\buses\b(.*?);")


def unit_deps(build, name83):
    """The 8.3 names a STAGED source depends on, from its `uses` clauses.

    Read from the staged copy, so the names have already been rewritten to
    their 8.3 form and match the filenames on disk. Units the compiler ships
    with -- Crt, Dos, System -- simply do not exist here and drop out.
    """
    p = build / name83
    if not p.exists():
        return []
    text = p.read_text(encoding="latin1", errors="replace")
    # strip comments, so a `uses` inside one cannot pull in a phantom
    text = re.sub(r"(?s)\{.*?\}|\(\*.*?\*\)", " ", text)
    out = []
    for clause in USES.findall(text):
        for word in re.split(r"[,\s]+", clause):
            cand = word.strip().upper()
            if cand and (build / (cand + ".PAS")).exists():
                out.append(cand + ".PAS")
    return out


def deps_first(build, sel):
    """`sel` plus everything it needs, units before the things that use them."""
    order, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        for d in unit_deps(build, name):
            visit(d)
        order.append(name)

    for t in sel:
        visit(t)
    return order


def ordered(cfg, build, staged, selection):
    """The compile order, by whichever strategy the target declares.

    `uses` derives it from the staged sources and is right where the graph is
    the truth; `declared` takes the config's list verbatim and is right where a
    person has worked the order out against something the graph does not say --
    a circular reference broken by a bootstrap pass, for one.
    """
    sel = staged
    if selection:
        sel = [t for t in staged if t.split(".")[0] in selection]
        if not sel:
            raise SystemExit(
                "  no target matches %s; known: %s"
                % (selection, ", ".join(t.split(".")[0] for t in staged)))
    if cfg["order"]["mode"] == "declared":
        return sel
    return deps_first(build, sel)


# ---------------------------------------------------------------------------
# The batch file


def write_batch(cfg, build, targets, compiler, extra, keep):
    """Assembler first where a module exists, then the compiler per target.

    Every step appends to a log INSIDE the mounted drive, because DOSBox-X is a
    GUI application and writes nothing to the host's stdout. The log is read
    back from the host afterwards.
    """
    comp = cfg["compiler"][compiler]
    tpc = machine("toolchain." + compiler, comp.get("exe"))
    log = cfg.get("log", "BUILD.LOG")
    lines = ["@echo off"]
    if not keep and cfg.get("wipe_tpu", True):
        # Wiping from the host and wiping inside DOSBox are two erasures, and
        # a fix that did only the first left stale .TPUs behind.
        lines.append("del *.TPU > NUL")
    lines.append("echo === build > %s" % log)

    asm = cfg["assembler"]
    if asm.get("exe") or asm.get("flags"):
        tasm = machine("toolchain.tasm", asm.get("exe"))
        out = (cfg.get("stage", {}) or {}).get("output")
        # Every directory holding .ASM: the build root, plus any staged
        # verbatim. ASSEMBLED FROM INSIDE ITS OWN DIRECTORY, because TASM
        # resolves INCLUDE against the current directory and one of these
        # modules includes a generated table. Passing `ASM\X.ASM` instead
        # would look for that table in the root and not find it.
        where = [(build, "")]
        for rel in (cfg.get("stage", {}) or {}).get("verbatim", []):
            d = build / pathlib.Path(rel).name.upper()
            if d.is_dir():
                where.append((d, d.name))
        for d, sub in where:
            for name in sorted(x.name for x in d.glob("*.ASM")):
                # BY PATH, WITH AN INCLUDE FLAG -- no `cd`. This used to change
                # into the directory and assemble a bare filename, on the
                # assumption that an assembler resolves INCLUDE against the
                # source file's own directory and so needed no help. MEASURED,
                # and it does not: `TASM ASM\\DEMOMATH.ASM` answers
                # `Can't locate file: COSTAB.INC` for an include sitting beside
                # the file that includes it. What it wants is the include flag,
                # and with `/IASM` the same command assembles cleanly.
                #
                # Worth having for what it deletes rather than what it adds: no
                # cd, no cd back, and no log path that has to know how deep the
                # batch currently is -- which is where a `..\\D:\\BUILD.LOG` that
                # DOS could not open silently swallowed every assembler message.
                src = ("%s\\%s" % (sub, name)) if sub else name
                inc = (" %s%s" % (asm.get("include_flag", "/I"), sub)) if sub else ""
                obj = (", %s\\%s" % (out, name.replace(".ASM", ".OBJ"))) if out else ""
                lines.append("echo. >> %s" % log)
                lines.append("echo ---- %s >> %s" % (src, log))
                lines.append("%s %s%s %s%s >> %s"
                             % (tasm, asm.get("flags", ""), inc, src, obj, log))
                lines.append("if errorlevel 1 echo ** FAILED >> %s" % log)
                lines.append("if not errorlevel 1 echo ** OK >> %s" % log)

    switches = (comp.get("switches", "") + extra).strip()
    for t in targets:
        for pre in comp.get("prepass", []):
            # A pass emitted immediately BEFORE a named target, with its own
            # switches. It exists for a circular unit reference: whichever unit
            # compiles first needs the other's .TPU, so one of them is built
            # once in a cut-down form for the other to compile against. It has
            # to sit here rather than at the top of the batch, because the
            # cut-down unit still needs everything below it in the order.
            if pre["before"] != t:
                continue
            lines.append("echo. >> %s" % log)
            lines.append("echo ---- %s (%s) >> %s"
                         % (pre["target"], pre.get("why", "prepass"), log))
            lines.append("%s %s %s %s >> %s"
                         % (tpc, switches, pre.get("switches", ""),
                            pre["target"], log))
        lines.append("echo. >> %s" % log)
        lines.append("echo ---- %s >> %s" % (t, log))
        lines.append("%s %s %s >> %s" % (tpc, switches, t, log))
        lines.append("if errorlevel 1 echo ** FAILED >> %s" % log)
        lines.append("if not errorlevel 1 echo ** OK >> %s" % log)
    lines.append("exit")
    (build / "BUILD.BAT").write_text("\r\n".join(lines) + "\r\n",
                                     encoding="ascii")


def write_conf(cfg, build, conf, compiler, root=None):
    """The DOSBox-X config, generated so no machine path is ever committed.

    `[dosbox.mount]` adds drives beyond the staging one: LETTER = "path",
    resolved against the project root. It exists so a session can reach a
    directory the build does NOT own -- a packaged demo, a folder of originals
    to run side by side -- without a machine path being typed into a committed
    file or a drive being mounted by hand every time.

    A missing directory is skipped with a line saying so, rather than mounted:
    DOSBox-X will mount a path that does not exist and then answer "Illegal
    command" for everything on it, which reads as the program being broken.
    """
    comp = cfg["compiler"][compiler]
    lines, doc = [], []
    for letter, rel in sorted((cfg.get("dosbox", {}).get("mount", {})).items()):
        d = (pathlib.Path(root) / rel) if root else pathlib.Path(rel)
        if d.is_dir():
            lines.append("mount %s %s" % (letter.upper(), d))
            doc.append("#     %s:  %s" % (letter.upper(), d))
        else:
            doc.append("#     %s:  NOT MOUNTED -- %s does not exist"
                       % (letter.upper(), d))
    conf.write_text(CONF_TEMPLATE.format(
        hdd=machine("dosbox.hdd"),
        build=str(build),
        drive=cfg.get("drive", "D"),
        title=cfg.get("title", "build"),
        binpath=bin_dir(cfg, compiler),
        mounts="".join(l + "\n" for l in lines),
        mountdoc="".join(l + "\n" for l in doc),
    ), encoding="ascii")


# ---------------------------------------------------------------------------
# Running, reporting, installing


def write_overlay(cfg, root, build, compiler, out):
    """An [autoexec]-only config: the mounts, the PATH, and where to land.

    WHY AN OVERLAY. A DOSBox config worth keeping is a few hundred tuned
    settings and nothing should regenerate those -- but the moment it also
    carries `mount D <somebody's checkout>` it is a committed file full of
    machine paths, which is what this project spent a ticket removing from two
    other files. Splitting it settles both: the settings stay committed and
    hand-edited, the mounts are generated from the answers file, and DOSBox-X is
    given both with -conf.

    THE OVERLAY GOES SECOND, and the design does not rest on knowing what
    DOSBox-X does with two [autoexec] sections. If it appends them, the base
    file's run first and the overlay's follow; if the later config wins outright,
    the overlay's are the only ones. Either way the overlay takes effect --
    because the base file's [autoexec] is kept empty of commands, which is the
    one thing that makes both behaviours the same. Do not put a command in it.

    Nothing is launched from here. The maintainer runs DOSBox; this writes the
    file and the caller prints the command.
    """
    comp = cfg["compiler"][compiler]
    dosbox = cfg.get("dosbox", {})
    lines = ["# GENERATED by kit/tools/pascal/build.py --interactive.",
             "# The settings live in the base config; this is the mounts alone,",
             "# so no machine path is ever committed. Do not edit it.",
             "",
             "[autoexec]",
             "mount C %s" % machine("dosbox.hdd"),
             "mount %s %s" % (cfg.get("drive", "D"), build)]
    for letter, rel in sorted(dosbox.get("mount", {}).items()):
        d = pathlib.Path(root) / rel
        if d.is_dir():
            lines.append("mount %s %s" % (letter.upper(), d))
        else:
            lines.append("REM %s: not mounted, %s does not exist"
                         % (letter.upper(), d))

    # The DOS-side bin directories, from the same answers the build compiles
    # with, so the interactive prompt cannot disagree with the build about which
    # compiler is installed. That disagreement is not theoretical: the committed
    # config put a TP bin directory on the PATH that had since been renamed, so
    # TPC at the prompt answered "Bad command or filename".
    path = [bin_dir(cfg, compiler)]
    try:
        tasm = machine("toolchain.tasm", cfg.get("assembler", {}).get("exe"))
        if tasm and ":" in tasm:
            path.append(tasm.rsplit(SEP, 1)[0])
    except project.Missing:
        pass
    path = [x for x in path if x]
    if path:
        lines.append("set PATH=%PATH%;" + ";".join(path))

    if dosbox.get("land"):
        lines.append("%s:" % dosbox["land"].rstrip(":").upper())
    for text in dosbox.get("banner", []):
        lines.append("echo." if not text else "echo   %s" % text)
    out.write_text(NL.join(lines) + NL, encoding="ascii")
    return out


def run_dosbox(root, conf, logfile, timeout):
    if logfile.exists():
        logfile.unlink()
    cmd = [str(machine("dosbox.exe")), "-conf", str(conf), "-silent", "-exit"]
    try:
        subprocess.run(cmd, cwd=str(root), timeout=timeout,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.TimeoutExpired:
        return "", "TIMEOUT -- dosbox-x did not exit"
    if not logfile.exists():
        return "", "no log produced -- the autoexec did not run"
    return logfile.read_text(encoding="latin1", errors="replace"), None


ERROR = re.compile(r"^([A-Z0-9_\\]+\.(?:PAS|INC))\((\d+)\): ((?:Error|Fatal).+)$",
                   re.M)


def report(build, out):
    """Print each failure with the source around it.

    The compiler prints the offending line but not its context, and the context
    is usually what identifies the fix.
    """
    shown = 0
    for m in ERROR.finditer(out):
        fname, line, msg = m.group(1), int(m.group(2)), m.group(3)
        print("")
        print("%s(%d): %s" % (fname, line, msg))
        f = build / fname
        if f.exists():
            src = f.read_text(encoding="latin1", errors="replace").splitlines()
            for n in range(max(1, line - 4), min(len(src), line + 2) + 1):
                print("  %s %4d %s" % (">>" if n == line else "  ", n,
                                       src[n - 1].rstrip()))
        shown += 1
    return shown


def install(cfg, root, build, targets):
    """Copy what just built into the directory the harnesses are run from.

    Staging wipes the build directory, so an executable only survives until the
    next build of anything else. Copying it by hand afterwards is easy to
    forget and, worse, easy to GET AWAY with: the run directory still holds the
    previous build under the same name, so it launches, behaves like the old
    code, and the change looks as though it did nothing.
    """
    spec = cfg["install"]
    if not spec:
        return
    try:
        run = root / (spec.get("to") or project.get("layout.built"))
    except project.Missing:
        return
    if not run.is_dir():
        print("  no %s -- nothing installed" % run)
        return
    products = outdir(cfg, build, keep=True)
    # `[install.as]` renames on the way out: STEM = "installed name". A DOS
    # compiler names its executable after the source and offers no way to say
    # otherwise, so a project whose shipped artefacts are called something a
    # compiler cannot produce -- NEUROSIS.001, an extension that is not even
    # .EXE -- has to rename at exactly this point. Naming it here rather than
    # renaming the SOURCE keeps the source called what the unit is called,
    # which is what every other instrument reads it by.
    as_named = cfg["install"].get("as", {})
    for t in targets:
        stem = t.split(".")[0]
        exe = products / (stem + ".EXE")
        if exe.exists():
            name = as_named.get(stem, exe.name)
            shutil.copy(exe, run / name)
            print("  installed %s/%s  (%d bytes)%s"
                  % (run.name, name, exe.stat().st_size,
                     "" if name == exe.name else "   <- %s" % exe.name))
    for pat in spec.get("alongside", []):
        for f in sorted(build.glob(pat)):
            shutil.copy(f, run / f.name)


# ---------------------------------------------------------------------------


def main(argv):
    args = project.positionals(argv[1:], ("--compiler", "--timeout"))
    if not args:
        sys.stdout.write("usage: build.py CONFIG.toml [TARGET...] "
                         "[--selftest] [--keep] [--compiler NAME] [--sw=X]\n"
                         "       build.py CONFIG.toml --interactive\n")
        return 2

    def opt(name, default=None):
        flag = "--" + name
        return argv[argv.index(flag) + 1] if flag in argv else default

    cfg = read_config(args[0])
    root = pathlib.Path(args[0]).resolve().parent
    while not (root / "kit.toml").exists() and root != root.parent:
        root = root.parent

    selftest = "--selftest" in argv
    keep = "--keep" in argv
    compiler = opt("compiler") or cfg["compiler"].get("default") or "tp7"
    if compiler not in cfg["compiler"] or not isinstance(
            cfg["compiler"][compiler], dict):
        return project.complain("no compiler called %r in %s -- have %s"
                                % (compiler, args[0],
                                   ", ".join(k for k, v in cfg["compiler"].items()
                                             if isinstance(v, dict))))
    # `--sw=/$G-` appends to the recorded switch line, for testing one switch
    # against the binary without editing the configuration it is recorded in.
    extra = "".join(" " + a[5:] for a in argv if a.startswith("--sw="))
    selection = [a.upper().replace(".PAS", "") for a in args[1:]]

    build = root / cfg.get("build", "build")
    if cfg.get("subdir"):
        build = build / cfg["subdir"]

    # --interactive COMPILES NOTHING. It writes the mounts overlay and prints
    # the command, because the person who runs DOSBox interactively is the one
    # sitting in front of it. Writing the file is the part a tool can do without
    # a machine path reaching a committed file.
    if "--interactive" in argv:
        dosbox = cfg.get("dosbox", {})
        base = dosbox.get("base_conf")
        if not base:
            return project.complain(
                "%s has no [dosbox] base_conf, so there is no config to overlay"
                % args[0])
        out = root / (dosbox.get("overlay") or "MOUNTS.CFG")
        write_overlay(cfg, root, build, compiler, out)
        print("  wrote %s" % out)
        for line in out.read_text(encoding="ascii").split(NL):
            if line and not line.startswith("#"):
                print("      %s" % line)
        try:
            exe = machine("dosbox.exe")
        except project.Missing as exc:
            return project.complain(exc)
        # IT PRINTS AND DOES NOT LAUNCH. An interactive session belongs to the
        # person sitting in front of it, and their launcher is theirs to write:
        # for a DOSBox-X that wants its own directory as the working one, a
        # two-line batch file does that better than a flag here would.
        cmd = [str(exe), "-conf", str(root / base), "-conf", str(out)]
        print("\n  run it yourself -- the overlay goes SECOND, so its mounts "
              "run after the base file's autoexec:\n")
        print("  " + " ".join('"%s"' % c if " " in c else c for c in cmd))
        return 0

    # Lint FIRST where the project has a linter. The compiler reports a
    # nested-comment defect dozens of lines from its cause, so catching it here
    # saves a wild goose chase -- that has bitten this project three times.
    #
    # The linter's CHECKER is imported and run over the files about to be
    # staged, rather than the script being run as a command. That is not
    # fastidiousness: one repository's copy of `paslint.py` hardcodes a source
    # directory that does not exist there, so invoking it reports "0 problem(s)
    # in 0 file(s)" and passes. A check that cannot fail is worse than none,
    # and the script it replaces avoided this the same way.
    if cfg.get("lint") and not selftest:
        if lint_sources(root, cfg):
            print("build refused: fix the above first")
            return 2

    staged = stage(cfg, root, build, compiler, selftest, keep)
    if not staged:
        print("nothing staged")
        return 1
    targets = staged if selftest else ordered(cfg, build, staged, selection)
    write_batch(cfg, build, targets, compiler, extra, keep)
    conf = build / "DOSBUILD.CFG"
    write_conf(cfg, build, conf, compiler, root)

    print("compiler: %s%s" % (compiler, "  extra: " + extra if extra else ""))
    print("staged %d file(s) into %s: %s"
          % (len(targets), build.name, ", ".join(targets)))

    logname = cfg.get("log", "BUILD.LOG").split("\\")[-1]
    out, err = run_dosbox(root, conf, build / logname,
                          int(opt("timeout") or cfg.get("timeout", 180)))
    if err:
        print("FAILED:", err)
        return 1

    # A MISSING COMPILER IS A FAILED BUILD, and nothing downstream can tell.
    # See tool_missing: DOS leaves errorlevel at zero for a command it cannot
    # find, so the batch stamps ** OK and every other signal below agrees.
    missing_tool = tool_missing(
        machine("toolchain." + compiler, cfg["compiler"][compiler].get("exe")))
    if missing_tool:
        print("")
        print("BUILD FAILED -- the compiler is not there. %s does not exist on"
              % missing_tool)
        print("the mounted drive (dosbox.hdd). DOS does not set errorlevel for a")
        print("command it cannot find, so every unit would have been stamped")
        print("** OK and this build would have reported success without")
        print("compiling anything. Fix toolchain.%s in kit.local.toml."
              % compiler)
        return 1

    failed = report(build, out)

    # The batch file stamps ** FAILED / ** OK from the errorlevel after every
    # invocation. That verdict cannot be missed by a pattern, so it OVERRIDES
    # a clean parse: a compiler message without a filename -- "Error 49: Data
    # segment too large." is one -- matches nothing above and would otherwise
    # be reported as a successful build.
    # The DOS message, as a backstop for anything tool_missing cannot reach --
    # a tool on a drive that is not the mounted image, or a PATH lookup.
    # BOTH SPELLINGS. DOSBox-X prints "Bad command or filename" -- measured 4
    # Sep 2026 by pointing toolchain.tasm at a directory that does not exist,
    # which failed the build exit 1 and proved this backstop carries the
    # assembler, since tool_missing above covers only the compiler. MS-DOS
    # writes "Bad command or file name", and a build run under anything but
    # DOSBox-X would say that instead. Checking one spelling and quoting the
    # other in two comments is how a working guard gets "corrected" into one
    # that cannot fire.
    dos_lost = [l for l in out.rstrip().splitlines()
                if "Bad command or filename" in l
                or "Bad command or file name" in l]
    if dos_lost:
        print("")
        print("BUILD FAILED -- DOS could not run a command. The log says so and")
        print("errorlevel does not, which is why this is checked by text:")
        print("  " + dos_lost[0].strip())
        return 1

    stamped = out.count("** FAILED")
    if stamped and not failed:
        print("")
        print("The compiler reported failure but printed no FILE(LINE) error "
              "line, so there is no source context to show. The log's tail:")
        for line in out.rstrip().splitlines()[-12:]:
            print("  " + line)
        failed = stamped

    if failed:
        # THE VERDICT GOES LAST. `report` prints each error with a few lines of
        # source around it, so before this the final line of a failed build was
        # a fragment of somebody's `uses` clause -- and a failed build looks
        # exactly like a successful one to anyone reading the tail. Four
        # commits went by with a broken unit, a cascade into three more
        # targets, and stale executables being measured as if they were fresh.
        print("BUILD FAILED -- %d error(s) above. NOTHING WAS INSTALLED, so "
              "anything in the output directory is STALE and any measurement "
              "of it is meaningless." % failed)
        return 1
    ok = re.findall(r"^(\d+) lines,", out, re.M)
    if ok:
        print("all %d target(s) compiled: %s"
              % (len(ok), ", ".join(n + " lines" for n in ok)))
    else:
        print(out)
    install(cfg, root, build, targets)
    # AND WHAT A SELFTEST COST, said after the success line rather than before
    # it. stage() wipes the build directory, so a selftest leaves it holding
    # HELLO.* and nothing else: `artefact --check` then answers "cannot read a
    # side" and `routines` answers "nothing built", both correctly and neither
    # naming the cause. That is a check list going red for a reason nothing on
    # it can explain -- measured 4 Sep 2026 on two host roots, where the only
    # surviving evidence was HELLO.PAS sitting in build/.
    #
    # It goes HERE because a run that ends on "all 1 target(s) compiled" reads
    # as unqualified success, which is the shape the BUILD FAILED branch above
    # is careful to avoid.
    if selftest and not keep:
        print("the toolchain works. NOTE the build directory now holds only "
              "the self-test:\n"
              "  artefact --check, routines and linkbytes will fail until a "
              "real build is run.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
