"""The ratchet: a lock that rises by itself and will not fall quietly.

There is exactly one ratchet across the 55 scripts in the two repos --
`asmverify.py`'s `EXPECTED` -- and everything else merely reports. Issue #9
settled that the ratchet belongs to the shared compare tool rather than to one
project's driver, and issue #13 settled what it becomes. This is that.

WHAT THE OLD ONE DID, and the three holes in it:

    EXPECTED = { "DEMOVT.MusicDetect": 64, ... }

a byte-match length per routine, held as a DICT LITERAL INSIDE THE TOOL. Fewer
bytes matching fails the run. More bytes matching only prints "longer than the
locked 40" -- the number does not rise on its own; a person runs `--learn` and
pastes a fresh table in.

  1. THE LOCK SITS STALE-LOW. A routine improved from 40 bytes to 64 stays
     locked at 40 until somebody pastes, and can then fall back to 40 and pass.
  2. DELETING A MARKER MAKES A ROUTINE VANISH from the report and nothing
     complains, so the cheapest way to make the build pass is to stop
     measuring.
  3. THE LOCK RECORDS NO REASON, so a lowered number looks like any other edit.

WHAT THIS DOES INSTEAD:

  * the lock lives in a COMMITTED TOML FILE, readable by other tools, so
    lowering it is a visible data change rather than a source edit;
  * it RISES AUTOMATICALLY. A byte-match length is measured against a fixed
    1994 binary, so an increase is unambiguously real and there is no judgement
    worth preserving by making a human paste it;
  * it RATCHETS COVERAGE too. The number of declared targets may not fall,
    which is the hole that let a marker be deleted;
  * it RATCHETS THE ACHIEVED RUNG, with the escape on the TARGET and never on
    the measurement. Achieved is computed and cannot be hand-edited. A
    legitimate drop -- a routine deliberately rewritten, its stance changed to
    `equivalent` -- is expressed by LOWERING THE TARGET with a reason. The way
    out is a declared decision, not an edit to a number;
  * NOTHING FAILS SILENTLY AND NOTHING PASSES SILENTLY (issue #15). Every rise
    is printed. Every lowering needs prose and is printed.

An unlocked routine still does not fail the run. Failing would mean a routine
could not be marked until it had already been verified, which inverts the
workflow -- the gap is reported instead.

Encoding, per CLAUDE.md: utf-8 explicitly, and LF on write.

    python toolkit/pascal/ratchet.py status.toml --coverage 71
    python toolkit/pascal/ratchet.py status.toml --coverage 71 --write
"""
import io
import os
import sys

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover -- 3.11+ per pyproject.toml
    tomllib = None

RUNGS = ("R0", "R1", "R2", "R3", "R4", "R5", "R6", "R7")


def rung_index(name):
    try:
        return RUNGS.index(str(name).upper())
    except ValueError:
        return -1


def load(path):
    if not os.path.exists(path):
        return {}
    with io.open(path, "rb") as fh:
        return tomllib.load(fh)


def dump(status):
    """Serialise our fixed schema. Hand-written on purpose: tomllib reads but
    does not write, and adding a TOML writer as a dependency to emit four key
    shapes would be a poor trade."""
    out = ["# Generated by toolkit/pascal/ratchet.py. The lock is DATA, not code,",
           "# so a lowering shows up as a visible change here (issue #13).",
           "#",
           "# `matched` and `achieved` are MEASURED and must never be hand-edited.",
           "# To accept a genuine regression, lower `target` and give a `reason`.",
           ""]
    cov = status.get("coverage", {})
    out.append("[coverage]")
    out.append("targets = %d" % int(cov.get("targets", 0)))
    if cov.get("reason"):
        out.append("reason = %s" % toml_str(cov["reason"]))
    out.append("")
    for key in sorted(status.get("routine", {})):
        row = status["routine"][key]
        out.append("[routine.%s]" % toml_str(key))
        for field in ("matched", "target", "achieved", "reason"):
            if field in row and row[field] not in (None, ""):
                val = row[field]
                out.append("%s = %s" % (field, val if isinstance(val, int)
                                        else toml_str(val)))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def toml_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def check(old, new):
    """Compare a previous status against fresh measurements.

    Returns (failures, rises, notes). `new` carries only measured values:
    coverage, and per-routine `matched` / `achieved`.
    """
    failures, rises, notes = [], [], []

    old_cov = int(old.get("coverage", {}).get("targets", 0))
    new_cov = new.get("coverage", {}).get("targets")
    if new_cov is not None:
        new_cov = int(new_cov)
        if new_cov > old_cov:
            rises.append("coverage %d -> %d target(s)" % (old_cov, new_cov))
        elif new_cov < old_cov:
            reason = new.get("coverage", {}).get("reason")
            if reason:
                notes.append("coverage lowered %d -> %d, reason given: %s"
                             % (old_cov, new_cov, reason))
            else:
                failures.append(
                    "COVERAGE FELL %d -> %d target(s) and no reason was given. "
                    "Deleting a marker is not progress." % (old_cov, new_cov))

    old_rows = old.get("routine", {})
    for key in sorted(new.get("routine", {})):
        fresh, prev = new["routine"][key], old_rows.get(key, {})
        if not prev:
            notes.append("%s: not locked yet -- reported, not failed" % key)
            continue

        if "matched" in fresh and "matched" in prev:
            a, b = int(prev["matched"]), int(fresh["matched"])
            if b > a:
                rises.append("%s: matched %d -> %d" % (key, a, b))
            elif b < a:
                failures.append("%s: MATCHED FELL %d -> %d bytes -- regression"
                                % (key, a, b))

        if "achieved" in fresh and "achieved" in prev:
            a, b = rung_index(prev["achieved"]), rung_index(fresh["achieved"])
            if b > a:
                rises.append("%s: achieved %s -> %s"
                             % (key, prev["achieved"], fresh["achieved"]))
            elif b < a:
                # The escape is on the TARGET, never on the measurement.
                lowered = (rung_index(fresh.get("target", prev.get("target")))
                           < rung_index(prev.get("target", "R7")))
                reason = fresh.get("reason") or prev.get("reason")
                if lowered and reason:
                    notes.append("%s: achieved %s -> %s, accepted because the "
                                 "target was lowered: %s"
                                 % (key, prev["achieved"], fresh["achieved"], reason))
                else:
                    failures.append(
                        "%s: ACHIEVED FELL %s -> %s. To accept this, lower the "
                        "target and give a reason -- do not edit the measurement."
                        % (key, prev["achieved"], fresh["achieved"]))
    return failures, rises, notes


def merge(old, new):
    """Apply rises into the stored status. Only raises; never lowers."""
    out = {"coverage": dict(old.get("coverage", {})),
           "routine": {k: dict(v) for k, v in old.get("routine", {}).items()}}
    nc = new.get("coverage", {}).get("targets")
    if nc is not None:
        out["coverage"]["targets"] = max(int(nc),
                                         int(out["coverage"].get("targets", 0)))
    for key, fresh in new.get("routine", {}).items():
        row = out["routine"].setdefault(key, {})
        if "matched" in fresh:
            row["matched"] = max(int(fresh["matched"]), int(row.get("matched", 0)))
        if "achieved" in fresh:
            if rung_index(fresh["achieved"]) >= rung_index(row.get("achieved", "R0")):
                row["achieved"] = fresh["achieved"]
        for field in ("target", "reason"):
            if field in fresh:
                row[field] = fresh[field]
    return out


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    if not args:
        sys.stdout.write("usage: ratchet.py <status.toml> [--coverage N] "
                         "[--measured file.toml] [--write]\n")
        return 2
    path, write = args[0], "--write" in argv

    new = {"coverage": {}, "routine": {}}
    if "--coverage" in argv:
        new["coverage"]["targets"] = int(argv[argv.index("--coverage") + 1])
    if "--measured" in argv:
        measured = load(argv[argv.index("--measured") + 1])
        new["coverage"].update(measured.get("coverage", {}))
        new["routine"] = measured.get("routine", {})

    old = load(path)
    failures, rises, notes = check(old, new)

    for line in rises:
        sys.stdout.write("  RISE     %s\n" % line)
    for line in notes:
        sys.stdout.write("  note     %s\n" % line)
    for line in failures:
        sys.stdout.write("  FAIL     %s\n" % line)

    if write and not failures:
        io.open(path, "w", encoding="utf-8", newline="\n").write(dump(merge(old, new)))
        sys.stdout.write("  written  %s\n" % path)

    sys.stdout.write("%d failure(s), %d rise(s), %d note(s)%s\n"
                     % (len(failures), len(rises), len(notes),
                        "" if write else " -- not written, pass --write"))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
