"""The status register's one serializer, so no tool can drop another's section.

`status.toml` is written by three tools -- ratchet.py (coverage, routines),
observe.py (observations) and plan.py (the plan). Each used to carry its own
dump(), and that duplication had already produced the defect this module
exists to prevent: ratchet.py's dump knew nothing of [observation.*], so a
`ratchet.py --write` would have silently erased every recorded observation.
Issue #15's rule -- never fail silently OR pass silently -- applies to
serialization too: a writer that drops what it does not understand is a
silent failure waiting for the next section to be invented.

So: one dump() that knows every section of the register, and REFUSES loudly
on a section it does not know rather than dropping it. A tool that invents a
new section must teach this module about it first, which is the point.

Encoding, per CLAUDE.md: utf-8 explicitly, LF on write.
"""
import io
import os

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover -- 3.11+ per pyproject.toml
    tomllib = None

HEADER = [
    "# Generated by kit/tools/pascal/{ratchet,observe,plan}.py. The lock is",
    "# DATA, not code, so a lowering is a visible change here (issue #13).",
    "#",
    "# `matched`, `achieved` and every [observation.*] are MEASURED. Never",
    "# hand-edit them. To accept a regression, lower `target` with a `reason`.",
    "# [plan] is DECIDED: investigation order is the priority order.",
    "",
]

ROUTINE_FIELDS = ("matched", "target", "achieved", "reason")
OBSERVATION_FIELDS = ("harness", "tier", "outcome", "achieved", "observer",
                      "date", "confirmed_at", "fingerprint", "against", "note")
INVESTIGATION_FIELDS = ("name", "finding", "seen_in", "state", "resolution")
ROW_FIELDS = ("label", "investigation", "target", "cost", "note")
ARTEFACT_FIELDS = ("ours", "original", "compare", "sha256", "achieved",
                   "target", "measured_at", "reason", "note")

KNOWN_SECTIONS = ("coverage", "routine", "observation", "plan", "artefact")


def load(path):
    if not os.path.exists(path):
        return {}
    with io.open(path, "rb") as fh:
        return tomllib.load(fh)


def toml_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _emit(out, field, value):
    out.append("%s = %s" % (field, value if isinstance(value, int)
                            else toml_str(value)))


def dump(status):
    unknown = [k for k in status if k not in KNOWN_SECTIONS]
    if unknown:
        raise ValueError(
            "register.dump does not know section(s) %s and will not drop "
            "them silently. Teach register.py the section first." % unknown)

    out = list(HEADER)
    cov = status.get("coverage", {})
    if cov:
        out.append("[coverage]")
        out.append("targets = %d" % int(cov.get("targets", 0)))
        if cov.get("reason"):
            _emit(out, "reason", cov["reason"])
        out.append("")
    for key in sorted(status.get("routine", {})):
        row = status["routine"][key]
        out.append("[routine.%s]" % toml_str(key))
        for f in ROUTINE_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    for key in sorted(status.get("observation", {})):
        row = status["observation"][key]
        out.append("[observation.%s]" % toml_str(key))
        for f in OBSERVATION_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    for key in sorted(status.get("artefact", {})):
        row = status["artefact"][key]
        out.append("[artefact.%s]" % toml_str(key))
        for f in ARTEFACT_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    plan = status.get("plan", {})
    for inv in plan.get("investigation", []):
        out.append("[[plan.investigation]]")
        for f in INVESTIGATION_FIELDS:
            if inv.get(f) not in (None, ""):
                _emit(out, f, inv[f])
        out.append("")
    for key in sorted(plan.get("row", {})):
        row = plan["row"][key]
        out.append("[plan.row.%s]" % toml_str(key))
        for f in ROW_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def write(path, status):
    io.open(path, "w", encoding="utf-8", newline="\n").write(dump(status))
