"""The status register's one serializer, so no tool can drop another's section.

`status.toml` is written by three tools -- ratchet.py (coverage, routines),
observe.py (observations) and plan.py (the plan). Each used to carry its own
dump(), and that duplication had already produced the defect this module
exists to prevent: ratchet.py's dump knew nothing of [observation.*], so a
`ratchet.py --write` would have silently erased every recorded observation.
Issue #15's rule -- never fail silently OR pass silently -- applies to
serialization too: a writer that drops what it does not understand is a
silent failure waiting for the next section to be invented.

So: one dump() that knows every section of the register, and REFUSES loudly
on a section it does not know rather than dropping it. A tool that invents a
new section must teach this module about it first, which is the point.

Encoding, per CLAUDE.md: utf-8 explicitly, LF on write.
"""
import io
import os

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover -- 3.11+ per pyproject.toml
    tomllib = None

HEADER = [
    "# Generated by kit/tools/pascal/{ratchet,observe,plan}.py. The lock is",
    "# DATA, not code, so a lowering is a visible change here (issue #13).",
    "#",
    "# `matched`, `achieved` and every [observation.*] are MEASURED. Never",
    "# hand-edit them. To accept a regression, lower `target` with a `reason`.",
    "# [plan] is DECIDED: investigation order is the priority order.",
    "",
]

ROUTINE_FIELDS = ("matched", "target", "achieved", "reason")
OBSERVATION_FIELDS = ("harness", "tier", "outcome", "achieved", "observer",
                      "date", "confirmed_at", "fingerprint", "against", "note",
                      # A retired harness's row keeps every measured field and
                      # gains these two, so the report can say SUPERSEDED where
                      # it would otherwise say STALE for ever. Adding a field to
                      # observe.py without adding it HERE drops it on the next
                      # dump by any tool -- which is the whole reason this
                      # whitelist is in one place.
                      "superseded_by", "superseded_on",
                      # An observation can record the HASH of the binary
                      # that was watched, which is what lets a rename be
                      # told from a change. See observe.py --reaffirm.
                      "binary", "reaffirmed_on")
INVESTIGATION_FIELDS = ("name", "finding", "seen_in", "state", "resolution")
ROW_FIELDS = ("label", "investigation", "target", "cost", "note")
ARTEFACT_FIELDS = ("ours", "original", "compare", "sha256", "achieved",
                   "target", "measured_at", "reason", "note")

KNOWN_SECTIONS = ("coverage", "routine", "observation", "plan", "artefact")


def load(path):
    if not os.path.exists(path):
        return {}
    with io.open(path, "rb") as fh:
        return tomllib.load(fh)


# Every character a TOML basic string may not carry raw, and what it becomes.
# Backslash first: it is the escape for the rest.
_ESCAPES = [
    ("\\", "\\\\"),
    ('"', '\\"'),
    ("\n", "\\n"),
    ("\r", "\\r"),
    ("\t", "\\t"),
    ("\f", "\\f"),
    ("\b", "\\b"),
]


def toml_str(s):
    """Quote a value as a TOML basic string, ESCAPING WHAT TOML FORBIDS RAW.

    IT USED TO ESCAPE ONLY THE BACKSLASH AND THE QUOTE, and that made this
    serializer able to write a register it could not read back. A resolution
    written with an embedded newline -- an ordinary thing to do, since these are
    paragraphs of prose -- produced `Illegal character` from the TOML parser on
    the next read, and every tool that reads the register failed at once. The
    record IS the measurement here, so a serializer that can corrupt it is the
    worst defect in the set: nothing downstream can recover the text.

    Control characters below 0x20 that have no short escape are written as
    \\uXXXX rather than dropped, because silently losing a character from a
    resolution is the failure this function exists to prevent.
    """
    out = str(s)
    for raw, esc in _ESCAPES:
        out = out.replace(raw, esc)
    out = "".join(c if ord(c) >= 0x20 or c in "\\\"" else "\\u%04x" % ord(c)
                  for c in out)
    return '"' + out + '"'


def _emit(out, field, value):
    out.append("%s = %s" % (field, value if isinstance(value, int)
                            else toml_str(value)))


def dump(status):
    unknown = [k for k in status if k not in KNOWN_SECTIONS]
    if unknown:
        raise ValueError(
            "register.dump does not know section(s) %s and will not drop "
            "them silently. Teach register.py the section first." % unknown)

    out = list(HEADER)
    cov = status.get("coverage", {})
    if cov:
        out.append("[coverage]")
        out.append("targets = %d" % int(cov.get("targets", 0)))
        if cov.get("reason"):
            _emit(out, "reason", cov["reason"])
        out.append("")
    for key in sorted(status.get("routine", {})):
        row = status["routine"][key]
        out.append("[routine.%s]" % toml_str(key))
        for f in ROUTINE_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    for key in sorted(status.get("observation", {})):
        row = status["observation"][key]
        out.append("[observation.%s]" % toml_str(key))
        for f in OBSERVATION_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    for key in sorted(status.get("artefact", {})):
        row = status["artefact"][key]
        out.append("[artefact.%s]" % toml_str(key))
        for f in ARTEFACT_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    plan = status.get("plan", {})
    for inv in plan.get("investigation", []):
        out.append("[[plan.investigation]]")
        for f in INVESTIGATION_FIELDS:
            if inv.get(f) not in (None, ""):
                _emit(out, f, inv[f])
        out.append("")
    for key in sorted(plan.get("row", {})):
        row = plan["row"][key]
        out.append("[plan.row.%s]" % toml_str(key))
        for f in ROW_FIELDS:
            if row.get(f) not in (None, ""):
                _emit(out, f, row[f])
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def write(path, status):
    io.open(path, "w", encoding="utf-8", newline="\n").write(dump(status))
