"""The segment table of a map document, computed from the layout config.

    python kit/tools/pascal/segdoc.py LINK.toml OUT.md [--part NNN] [--check]

WHAT IT IS FOR. `coverage.py` measures a target against a denominator, and the
denominator is a document listing every segment and its size. Two of three
consumers here had no such document -- one never wrote one, the other names a
file that does not exist -- so neither could be measured at all, and the
absence looked like a tooling problem rather than a missing input.

The table is DERIVED, not transcribed. Every segment's extent is the NEXT
segment's base, and `end_at` closes the last one, which is the same arithmetic
every link instrument uses. A hand-written size beside a hand-written address
is two copies of one measurement, and they drift -- that is recorded in
link.toml's own header, and it is why this computes rather than asks.

WHAT IT CANNOT WRITE is the third column, what each segment IS. That is a
reading of the binary and no config holds it. Rows come out named from the
segment list and nothing more, so a person can annotate them afterwards --
and `--check` compares only the address and the size, leaving prose alone.
"""
import io
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import project                                    # noqa: E402

try:
    import tomllib
except ModuleNotFoundError:                       # pragma: no cover -- 3.11+
    import tomli as tomllib                       # type: ignore

BANNER = "<!-- the seg/bytes columns below are generated by segdoc.py -->"

# THE FILE SAYS HOW TO REGENERATE AND RE-CHECK ITSELF, because the check
# takes two paths and so cannot go on the session list, which is deliberately
# the same in every project. A generated file whose command lives only in a
# commit message is generated once and hand-edited thereafter.
HOWTO = ("<!-- regenerate: segdoc.py %s %s%s   |   verify: add --check -->")


def rows(spec):
    """(paragraph, bytes, name) per segment, ascending."""
    bounds = project.seg_bounds(spec)
    named = project.segments(spec)
    return [(para, (nxt - para) * 16, name)
            for (para, name), nxt in zip(named, bounds[1:])]


def tail_rows(spec, part):
    """The rows past the segment list: the runtime, then the data group.

    TWO REGIONS, NOT ONE, AND WHICH IS WHICH DEPENDS ON THE SEGMENT LIST.
    `end_at` closes the list and `dgroup_at` is where the data group starts,
    and the gap between them is the runtime library. A target that lists its
    runtime segments has no gap -- the two are equal and there is one row.
    A target that excludes them, because the runtime is not its to
    transcribe, has a gap the size of the whole runtime.

    Calling the whole tail "the data group" is wrong in the second case by
    exactly that much: 15,936 bytes attributed to data in one part of a
    nine-part target, of which 15,184 are Borland's runtime.
    """
    try:
        image = project.original(part, quiet=True)
        first = project.get("target.first_para", quiet=True)
    except project.Missing:
        return []
    raw = pathlib.Path(image).read_bytes()
    hdr = int.from_bytes(raw[8:10], "little") * 16
    size = len(raw) - hdr
    end, dg = spec["end_at"], spec.get("dgroup_at", spec["end_at"])
    out = []
    if dg > end:
        out.append((end, (dg - end) * 16,
                    "the runtime library -- not this target's to transcribe"))
    tail = size - (dg - first) * 16
    if tail > 0:
        out.append((dg, tail,
                    "the data group -- linked last, so it is the image's tail"))
    return out


def table(spec, part=None, cfg='LINK.toml', out='OUT.md'):
    r = rows(spec)
    extra = tail_rows(spec, part)
    howto = HOWTO % (cfg, out, '' if part is None else ' --part ' + part)
    out = ["## Segments", "",
           "%d segments, %d bytes%s."
           % (len(r), sum(b for _, b, _ in r),
              "".join(", then %s at `%04x`, %d bytes"
                      % (w.split(" --")[0], p_, b) for p_, b, w in extra)),
           "", BANNER, howto, "", "| seg | bytes | what |", "|---|---:|---|"]
    out += ["| `%04x` | %d | **%s** |" % (p, b, n.title()) for p, b, n in r]
    out += ["| `%04x` | %d | **%s |" % (p_, b, w.replace(" --", "** --", 1))
            for p_, b, w in extra]
    return chr(10).join(out) + chr(10)


def main(argv=()):
    args = project.positionals(argv, ("--part",))
    if len(args) < 2:
        sys.stdout.write("usage: segdoc.py LINK.toml OUT.md [--part NNN] "
                         "[--check]" + chr(10))
        return 2
    with io.open(args[0], "rb") as fh:
        cfg = tomllib.load(fh)
    try:
        spec = project.layout(cfg, project.option(argv, "part"))
    except project.Missing as exc:
        return project.complain(exc)

    body = table(spec, project.option(argv, "part"), args[0], args[1])
    out = pathlib.Path(args[1])

    if "--check" in argv:
        # A GENERATED FILE IS ONLY GENERATED WHILE SOMETHING COMPARES IT. The
        # rows are compared, not the whole file, because the third column is
        # meant to be written by a person afterwards.
        if not out.is_file():
            sys.stdout.write("  %s does not exist" % out + chr(10))
            return 1
        have = [l for l in out.read_text(encoding="utf-8").splitlines()
                if l.startswith("| `")]
        want = [l for l in body.splitlines() if l.startswith("| `")]
        key = lambda ls: [tuple(l.split("|")[1:3]) for l in ls]
        if key(have) != key(want):
            sys.stdout.write("  %s is out of date -- %d row(s) on disk, %d "
                             "computed" % (out, len(have), len(want)) + chr(10))
            return 1
        sys.stdout.write("  %s: %d row(s) agree with the layout config"
                         % (out, len(want)) + chr(10))
        return 0

    if out.is_file() and BANNER not in out.read_text(encoding="utf-8"):
        # REFUSING TO OVERWRITE A HAND-WRITTEN DOCUMENT. One consumer's map is
        # 1,288 lines of read binary with the table embedded in it; replacing
        # that with a computed table would destroy the reading to satisfy the
        # denominator.
        sys.stdout.write(
            "  %s exists and carries no generated banner, so it was written by "
            "hand -- refusing to replace it. Delete it deliberately, or point "
            "this at a new file." % out + chr(10))
        return 2

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8", newline=chr(10))
    sys.stdout.write("  wrote %s -- %d segment(s)"
                     % (out, len(rows(spec))) + chr(10))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]) or 0)
