"""Comments that carry reverse-engineering apparatus without saying so.

    python kit/tools/pascal/tagcheck.py src/*.PAS src/*.ASM
    python kit/tools/pascal/tagcheck.py src/*.PAS --quiet
    python kit/tools/pascal/tagcheck.py src/*.PAS --count

WHAT IT IS FOR. A reconstruction's source carries two kinds of prose that read
alike and serve opposite readers: the EVIDENCE for how something was learned,
and the EXPLANATION of what it does. A stripped copy meant for the second
reader has to lose the first, and no pattern can tell them apart -- the split is
a judgement, so it is written down as a tag.

Tagging is keep-by-default, which is the cheap way round: on the corpus this was
built for, half the comments carry no apparatus at all and never need touching.
The cost of keep-by-default is that a NEW untagged comment leaks. This is the
instrument for that, and it is the reason the arrangement is safe rather than
merely convenient.

## What counts as a tell

Only mechanical ones -- a `segment:offset`, a segmented `DS:$`/`CS:$` address,
the name of a
measuring tool, a `~~withdrawn~~` marker. Never prose style. A tool that
guessed at tone would cry wolf until it was ignored, and an instrument nobody
runs is worse than none.

## What is exempt, and why each

* **`[re]` paragraphs.** They are removed by the stripper, so what they hold
  cannot leak. This is the tag the tool exists to encourage.
* **`[1.39b]` paragraphs.** The original author's own words, quoted. They are
  the best explanation in such a tree and are kept deliberately.
* **A frame slot, in assembler only.** There it is the parameter's only name.
* **A `GENERATED by ...` banner.** The tool's name is the instruction.

**`[reading]` IS NOT EXEMPT, AND THAT IS THE POINT.** It marks a claim resting
only on someone's reading of the instructions, and it is KEPT in the stripped
copy so inferences stay visible and countable. Kept means it can leak, so it is
held to the same standard as untagged prose.

## The blind spot

It reports what a comment SAYS, never what the code does, so a paragraph can be
clean here and still be wrong about the program. And it stops at the text: a
trimmed prefix that forms a compiler directive changes what compiles and is
invisible to every reading of it. Only building the stripped copy sees that.
Run both.
"""

import io
import re
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import clean                                                      # noqa: E402

# The tells. Mechanical, every one -- a thing no explanation of behaviour needs.
TELLS = (
    (re.compile(r'\b[0-9a-fA-F]{4}:[0-9a-fA-F]{4}\b'), 'a segment:offset'),
    # ANY SEGMENT REGISTER, not just DS. `CS:$002C` names a constant in the
    # original's CODE segment and is an address by the same argument; knowing
    # only DS left 70 of them across 19 files that nothing could see.
    (re.compile(r'\b(?:DS|CS|ES|SS):\$[0-9a-fA-F]{2,4}\b'),
     'a segmented address'),
    (re.compile(r'\b\w+\.py\b'), 'a measuring tool'),
    (re.compile(r'~~'), 'a withdrawn claim'),
)

# **A FRAME SLOT IS APPARATUS IN PASCAL AND DOCUMENTATION IN ASSEMBLER**, so
# this tell is applied to one and not the other.
#
# In Pascal the parameter has a name, and `[BP+$0c] @Result` beside it says
# only where the compiler happened to put it -- which a reader of the stripped
# copy meets with no frame anywhere in sight. That was the first pilot's leak.
#
# In a hand-written assembler routine there IS no name. The routine is entered
# with its arguments on the stack and `[BP+8]` is the only way to refer to one,
# so a header reading `IN  [BP+8]  stereo flag` is the parameter list. Flagging
# it would push a tool towards deleting the only documentation those arguments
# have.
PASCAL_ONLY = ((re.compile(r'\[BP[-+]'), 'a stack frame slot'),)
EXEMPT = re.compile(r'^\s*\[(?:re|1\.39b)\]', re.I)
# **A GENERATED-FILE BANNER NAMES ITS TOOL FOR A REASON A READER NEEDS.**
# `GENERATED by emit_gain.py -- DO NOT EDIT` is the one line that stops
# somebody editing an output, and the tool name IS the instruction: it says
# where to make the change instead. Flagging it pushes towards deleting it.
BANNER = re.compile(r'^[ \t]*GENERATED by', re.I | re.M)
# BOTH PASCAL COMMENT FORMS. `(* *)` is where a corpus puts the prose that has
# to MENTION a compiler directive, because `{ }` cannot hold one -- so it
# clusters around the riskiest comments in the tree and knowing only braces
# made every one of them invisible here. See clean.py's note for the counts.
COMMENT = clean.COMMENT_ALL
# Words that cannot BEGIN a sentence, so one at the front of a trimmed line says
# the citation was inside the sentence rather than in front of it. See
# dangling() for why this is asked of the trims and not of the stripped copy.
JOINER_WORD = re.compile(r'^[ \t]*(?:[,;]|(?:and|or|to|but|so|nor'
                         r'|than|then|plus|beyond|through)\b)', re.I)


def paragraphs(text, asm):
    """(line number, paragraph) for every comment paragraph in the file.

    Pascal splits a { } comment on blank lines; assembler has no such grain, so
    a run of consecutive `;` lines is one paragraph and a trailing comment on a
    line of code is its own.
    """
    if not asm:
        for m in COMMENT.finditer(text):
            start = text[:m.start()].count('\n') + 1
            body = clean.delims(m.group(0))[1]
            off = 0
            for para in re.split(r'\n[ \t]*\n', body):
                yield start + body[:off].count('\n'), para
                off += len(para) + 2
        return
    # **A BARE `;` LINE ENDS A PARAGRAPH**, exactly as a blank line does inside
    # a Pascal comment, because that is what the stripper does. The two tools
    # have to agree on the grain or this one misreports: grouping a whole
    # header as one paragraph, it reported a tell that sits in a part already
    # tagged, and no amount of tagging would have silenced it.
    run, first = [], 0
    for n, line in enumerate(text.split('\n'), 1):
        s = line.strip()
        if s.startswith(';'):
            body = s[1:].lstrip()
            if not body:                     # the separator
                if run:
                    yield first, '\n'.join(run)
                    run = []
                continue
            if not run:
                first = n
            run.append(body)
            continue
        if run:
            yield first, '\n'.join(run)
            run = []
        if ';' in line:                      # a trailing note on a code line
            yield n, line.split(';', 1)[1].strip()
    if run:
        yield first, '\n'.join(run)


ANYTAG = re.compile(r'\[(?:re|reading)\]', re.I)


def inert(text, asm):
    """Tags that do NOTHING, which is the worst state a tag can be in.

    A tag is read at the START of a paragraph and nowhere else -- that is how
    the stripper decides, and it is deliberate: a tag buried mid-sentence would
    make the meaning of a paragraph depend on where somebody happened to put a
    marker. So a `[re]` on a continuation line is INERT.

    That is worse than an untagged paragraph, and it hides in the one place
    nothing looks. The apparatus stays in the stripped copy exactly as if it had
    never been marked, AND the marker itself is now visible in the copy meant
    for a reader who has never heard of it -- so it reads as a typo in the
    documentation. Neither the stripper nor the leak check can see it: the
    stripper looks only at paragraph starts, and the leak check EXEMPTS a
    paragraph whose start matches, so a paragraph with a mid-sentence tag is
    simply an untagged one to both.

    Measured on the corpus that found this: three of them, and one had survived
    a closed ticket's gate.

    The usual cause is a paragraph that opens with a rule of dashes -- the tag
    goes on the first line of PROSE, which is the second line of the paragraph.
    The fix is a blank line, making the prose its own paragraph.
    """
    bad = []
    for m in clean.COMMENT_ALL.finditer(text):
        op, body, cl = clean.delims(m.group(0))
        start = text[:m.start()].count('\n') + 1
        off = 0
        for para in re.split(r'\n[ \t]*\n', body):
            n = start + body[:off].count('\n')
            off += len(para) + 2
            if not ANYTAG.search(para) or EXEMPT.match(para):
                continue
            if re.match(r'^\s*\[reading\]', para, re.I):
                continue
            bad.append((n, 'AN INERT TAG', '[re]',
                        'tag is not at the paragraph start: '
                        + ' '.join(para.split())[:52]))
    return bad if not asm else []


def dangling(text, asm):
    """Trims that cut into a SENTENCE rather than off the front of one.

    The stripper takes a leading run of citations off a comment line, which is
    right almost always. But prose wraps, and a citation can land at the start
    of a line while sitting in the MIDDLE of a sentence:

        { THE ORDER IS THE ORIGINAL'S AND THE ADDRESSES CHAIN EXACTLY. ColOfs
          is at
          DS:$0172 and 402 bytes long, so it ends at $0303; ...

    Trimmed, that reads `ColOfs is at` / `and 402 bytes long` -- a sentence with
    its middle removed, shipped in the copy meant for a reader.

    **NOTHING ELSE IN THE GATE CAN SEE IT.** The leak check reports zero,
    because no tell survives -- the address is gone, which was the point. The
    stripper's own self-check compares CODE and passes, because no code changed.
    The build passes. Only reading the stripped copy finds it, and on a tree of
    84 files that is not a thing anybody does twice.

    The tell: take what the trim LEFT and ask whether it opens with a word that
    cannot open a sentence. A citation that really was a prefix is followed by a
    fresh clause; one that was mid-sentence is followed by the rest of it.

    AND ONLY WHERE A SENTENCE WAS RUNNING INTO IT, which is the condition that
    makes this usable rather than noise. An assembler line's trailing
    `{ 1118:094e  and on to row 2 }` trims to `{ and on to row 2 }` and reads
    perfectly well -- it is a column fragment, not prose. Asking the question of
    every line in the stripped copy gives 547 hits on this corpus, nearly all
    ordinary wrapping; asking it of the trims, with this condition, gives 11.
    """
    bad = []
    for m in clean.COMMENT_ALL.finditer(text):
        body = clean.delims(m.group(0))[1]
        if clean.address_only(body):
            continue                      # goes whole; nothing is left to break
        start = text[:m.start()].count('\n') + 1
        lines = body.split('\n')
        # A tagged paragraph is removed entire, so a trim inside one cannot
        # reach the deliverable. Track the tag per paragraph, not per line.
        tagged, in_tag = [], False
        for ln in lines:
            if not ln.strip():
                in_tag = False
            elif ANYTAG.match(ln.lstrip()[:8]) or EXEMPT.match(ln):
                in_tag = True
            tagged.append(in_tag)
        for k, ln in enumerate(lines):
            if tagged[k]:
                continue
            cut = clean.LEAD.sub('', ln)
            run = clean.cite_run(cut)
            if run:
                cut = ' ' + cut[run:]
            if cut == ln or not cut.strip() or not JOINER_WORD.match(cut):
                continue
            prev = lines[k - 1] if k else ''
            if prev.strip() and not re.search(r'[.!?:}]$|--$', prev.rstrip()):
                bad.append((start + k, 'A CUT SENTENCE', 'trim',
                            'left: ' + ' '.join(cut.split())[:52]))
    return bad


def check(path):
    """What LEAKS, which is not the same as what a comment contains.

    THE FIRST BUILD OF THIS TOOL SCANNED THE SOURCE AND CRIED WOLF: 2,296 hits
    across 34 files, and nearly all of them were address prefixes the stripper
    already removes on its own. An instrument that reports work already done is
    one nobody runs.

    So it strips first, with the stripper's own code rather than a second copy
    of the rules, and scans what comes out. What survives is what a reader of
    the stripped copy would actually meet.
    """
    text = io.open(path, encoding='utf-8', errors='replace').read()
    # BY CONTENT, NOT BY SUFFIX. `.INC` says nothing about grammar, and taking
    # every one for assembler applied the `;`-run grain to Pascal includes,
    # where `;` ends a statement -- reporting 0 over three files full of
    # apparatus. clean.is_asm reads the first non-blank line.
    asm = clean.is_asm(path, text)
    hits = inert(text, asm) + dangling(text, asm)
    text, _, _, _ = clean.clean_text(text.replace('\r\n', '\n'), asm=asm)
    for n, para in paragraphs(text, asm):
        if not para.strip() or EXEMPT.match(para) or BANNER.search(para):
            continue
        for pat, what in (TELLS if asm else TELLS + PASCAL_ONLY):
            m = pat.search(para)
            if m:
                hits.append((n, what, m.group(0), ' '.join(para.split())[:70]))
                break
    return hits


def main(argv):
    files = [a for a in argv if not a.startswith('--')]
    if not files:
        raise SystemExit(__doc__)
    quiet, count = '--quiet' in argv, '--count' in argv
    total = 0
    for f in files:
        hits = check(f)
        total += len(hits)
        if hits and not count:
            if not quiet:
                print("%s" % pathlib.Path(f).name)
            for n, what, tok, body in hits:
                print("  %-5d %-18s %-12s %s"
                      % (n, what, tok[:12], body))
    print()
    print("%d problem(s) in the stripped copy across %d file(s)"
          % (total, len(files)))
    if total:
        print("Tag each `[re]` if it is evidence, rewrite it if it is"
              " not, and split a cut sentence so the citation is not"
              " inside it.")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
